### ISSUE TITLE
Put the PyCon UK Society constitution (back!) on the website

### ISSUE THREAD

**Issue by snim2** [PyconUK/pyconuk.org#104]
The document can be found here (via Wayback):

https://web.archive.org/web/20110720143450/http://www.pyconuk.org/pdfs/pyconuk_constitution.pdf

/cc @zeth @ntoll

**Comment by ntoll** [comment]
On 06/08/15 19:12, Sarah Mount wrote:

> The document can be found here (via Wayback):
> 
> https://web.archive.org/web/20110720143450/http://www.pyconuk.org/pdfs/pyconuk_constitution.pdf
> 
> /cc @zeth https://github.com/zeth @ntoll https://github.com/ntoll
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyconUK/pyconuk.org/issues/104.

Awesomeness on stilts!

N.

**Comment by ntoll** [comment]
OK... I've downloaded that file and put it into a branch. Just the PDF in a static location. I'll add a page about the society tomorrow.

**Comment by ntoll** [comment]
Having now read the damn thing... it all looks eminently sensible. I'll make a proposal for changes relating to openness and anti-bus-number-1 in the appropriate way.

**Comment by inglesp** [comment]
@snim2 / @ntoll -- now that we've got https://github.com/PyconUK/PyConUKSociety, is there anything else that needs doing here?

**Comment by snim2** [comment]
Since #105 has been merged I think we can safely say this Issue is resolved.
