### ISSUE TITLE
The word "Register" is obscured on a Hudl

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk.org#14]
From Mary: "I use a Hudl2 and the word "Register" is hidden behind the Pycon UK graphic at the top centre of the web page."

**Comment by ghickman** [comment]
I've managed to replicate this between window widths 940px & 969px. It looks like the width breakpoints need changing so we use the alternative/mobile version once we hit 969px. I need to test this on mobile so will push a fix [hopefully] tomorrow.

Anyone else who gets to this first, please feel free to pick it up.
