### ISSUE TITLE
Some incorrect rooms on flat schedule

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk.org#146]
There are some incorrect rooms on the flat schedule.  In particular, several events (including Django Girls at 12:30 on Friday; Teachers' CPD at 13:30 on Friday; the Recruitment Clinic at 12:30 on Saturday; possibly others) are shown on the flat schedule as being in the PythonAnywhere room.

**Comment by moreati** [comment]
Looks like I've missed the case where `<td rowspan=n>` from a previous row shifts a `td` right in the current row. So the parser wrongly thinks DjangoGIrls is in the first column.

![image](https://cloud.githubusercontent.com/assets/174450/9714912/899a9de0-5553-11e5-8d9b-2eed7db47cca.png)

**Comment by zeth** [comment]
Would it have been easier if you parsed the doctree (rst2xml) rather than
the html? Just a suggestion.
