### ISSUE TITLE
Duplicate text on the venue page.

### ISSUE THREAD

**Issue by ntoll** [PyconUK/pyconuk.org#26]
See this:

http://www.pyconuk.org/venue/

The following paragraph appears _twice_ in two different locations:

"If you come by car, there are car parks to both left and right of the entrance (Use the right hand one please, to leave the left hand one for other building users). They are barrier-controlled; take a ticket from the machine, don't lose it, and if you hand it in at Reception they will be able to validate it so that you don't have to pay when you leave :-)"

Is there a good reason for this..?  ;-)

**Comment by ghickman** [comment]
I reckon we should remove this, most likely a copy/pasta error anyway ;)
