### ISSUE TITLE
Sponsorship page has incorrect name

### ISSUE THREAD

**Issue by snim2** [PyconUK/pyconuk.org#29]
The "Sponsor's Deliveries" section still names Sandra as the recipient of any sponsor swag, is that still correct?

**Comment by inglesp** [comment]
Well spotted -- see https://github.com/PyconUK/pyconuk.org/pull/33.

Let's keep this issue open until we have new delivery information.

**Comment by ntoll** [comment]
Hi,

We were asked to keep using Sandra's name by the people at the venue. It's yet another way for them to identify "stuff" is for us (if that makes sense).

I realise this makes absolutely no sense whatsoever. ;-)

**Comment by inglesp** [comment]
Brilliant.
