### ISSUE TITLE
Panel participants need updating

### ISSUE THREAD

**Issue by snim2** [PyconUK/pyconuk.org#47]
What it says on the title. The details in the schedule are from last year.

**Comment by zeth** [comment]
No that is this year's panel. Sculptor has to work with the marble he has got. Possibly won't have Van though if he is not coming.

**Comment by inglesp** [comment]
I presume we're talking about [this panel](http://www.pyconuk.org/abstracts/#the-pycon-uk-panel).  If so, have we asked any of the people on that list?

**Comment by zeth** [comment]
Well Van is probably not even coming and the rest, as Sarah said, are the
regulars (Russel Winder being the other one who is not listed), I will add
to the panel _during the conference_, basically we the crew just keep an
eye on who is witty during the conference.

Micheal Foord and Larry Hastings deal with technical python questions but
we ask the panelists to sum up the conference, so we will want Sarah from
the science track, someone from Djangogirls, someone from education track,
etc.
