### ISSUE TITLE
Venue page link to lodging goes to 2014 wiki.

### ISSUE THREAD

**Issue by nceder** [PyconUK/pyconuk.org#7]
I don't see any current info on lodging.

**Comment by snim2** [comment]
Normally we archive the previous years wiki at 2014.pyconuk.net. I think this issue has arisen because we haven't done that yet.

**Comment by ghickman** [comment]
This has been flagged [on twitter](https://twitter.com/DRMacIver/status/618056512032886784) too.

Do we have a more up to date list or does that need generating?

Who can archive the old page/wiki? And should we move the accommodation page to the website?

**Comment by inglesp** [comment]
The work for this has already been done, but the link on the venue page hasn't been updated.  See https://github.com/PyconUK/pyconuk.org/pull/59.

**Comment by ghickman** [comment]
@inglesp – thanks!
